import AppContainer from "@/components/app-container";
import LeftSideBar from "@/components/left-sidebar";
import RightSidebar from "@/components/right-sidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LLM web app with Generative UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex h-screen max-w-[1440px] m-auto bg-background overflow-hidden">
          <AppContainer>
            <LeftSideBar />
            {children}
            <RightSidebar />
          </AppContainer>
        </main>
      </body>
    </html>
  );
}
