"""fileid-identity

Revision ID: 1a3e21da035c
Revises: f0d5c46f1bee
Create Date: 2025-10-07 08:33:10.370533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a3e21da035c'
down_revision: Union[str, Sequence[str], None] = 'f0d5c46f1bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'file_id')
    # ### end Alembic commands ###
