"""files changes

Revision ID: 5974e18b52d9
Revises: f78619b0f75e
Create Date: 2025-10-07 06:55:01.609072

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5974e18b52d9"
down_revision: Union[str, Sequence[str], None] = "f78619b0f75e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column("files", sa.Column("content", sa.Text(), nullable=True))
  op.drop_column("files", "file_id")
  op.drop_column("files", "extracted_text")
  op.drop_column("files", "file_path")
  op.drop_column("files", "original_name")
  op.drop_column("files", "processed")
  op.drop_column("files", "file_size")
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column("files", sa.Column("file_size", sa.INTEGER(), autoincrement=False, nullable=False))
  op.add_column("files", sa.Column("processed", sa.VARCHAR(), autoincrement=False, nullable=True))
  op.add_column(
    "files", sa.Column("original_name", sa.VARCHAR(), autoincrement=False, nullable=False)
  )
  op.add_column("files", sa.Column("file_path", sa.VARCHAR(), autoincrement=False, nullable=False))
  op.add_column("files", sa.Column("extracted_text", sa.TEXT(), autoincrement=False, nullable=True))
  op.alter_column(
    "files",
    "file_id",
    existing_type=sa.Integer(),
    type_=sa.VARCHAR(),
    existing_nullable=False,
    autoincrement=True,
  )
  op.drop_column("files", "content")
  # ### end Alembic commands ###
