"""fileid-remove

Revision ID: f0d5c46f1bee
Revises: e22867a48940
Create Date: 2025-10-07 08:32:43.790161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d5c46f1bee'
down_revision: Union[str, Sequence[str], None] = 'e22867a48940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
